/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c8b0",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#574144",
        "background": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "on-error-container": "#93000a",
        "outline": "#827473",
        "secondary-fixed-dim": "#e9c349",
        "primary": "#70585b",
        "surface-container": "#efeeeb",
        "inverse-primary": "#debfc2",
        "surface-variant": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "tertiary-fixed": "#e4e4cc",
        "on-tertiary-container": "#585946",
        "surface-container-highest": "#e3e2e0",
        "surface": "#faf9f6",
        "on-primary-fixed": "#281719",
        "on-tertiary-fixed": "#1b1d0e",
        "surface-tint": "#70585b",
        "secondary-fixed": "#ffe088",
        "error": "#ba1a1a",
        "surface-dim": "#dbdad7",
        "surface-container-low": "#f4f3f1",
        "on-primary-container": "#695254",
        "on-surface-variant": "#504444",
        "tertiary-container": "#cfd0b8",
        "secondary": "#735c00",
        "outline-variant": "#d4c2c2",
        "inverse-surface": "#2f312f",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#debfc2",
        "on-error": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-tertiary-fixed-variant": "#474836",
        "primary-container": "#e6c7ca",
        "primary-fixed": "#fbdbde",
        "on-secondary-fixed": "#241a00",
        "secondary-container": "#fed65b",
        "inverse-on-surface": "#f2f1ee",
        "on-background": "#1a1c1a",
        "on-primary": "#ffffff",
        "tertiary": "#5e604d",
        "on-secondary-fixed-variant": "#574500",
        "surface-bright": "#faf9f6",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
